#!/usr/bin/env bash
set -euo pipefail

# PayCollectionBOT — Production installer (Ubuntu 24+)
# Usage: sudo bash install.sh

REPO_URL="https://github.com/DayiGorbay/PayCollectionBOT.git"
INSTALL_DIR="${PAYCOLLECTION_HOME:-/opt/paycollection}"
COMPOSE_FILE="docker-compose.production.yml"

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

log() { echo -e "${GREEN}[paycollection]${NC} $*"; }
warn() { echo -e "${YELLOW}[paycollection]${NC} $*"; }
fail() { echo -e "${RED}[paycollection]${NC} $*" >&2; exit 1; }

require_root() {
  if [[ "${EUID:-$(id -u)}" -ne 0 ]]; then
    fail "This installer must be run as root (sudo bash install.sh)."
  fi
}

rand_hex() {
  openssl rand -hex "$1"
}

prompt_required() {
  local var_name="$1"
  local prompt="$2"
  local value=""
  while [[ -z "${value}" ]]; do
    read -r -p "${prompt}: " value
  done
  printf -v "${var_name}" '%s' "${value}"
}

prompt_telegram_proxy() {
  local answer=""
  read -r -p "Do you want to use Telegram Proxy? (y/n): " answer
  if [[ "${answer}" =~ ^[Yy]$ ]]; then
    BOT_PROXY_ENABLED=true
    prompt_required BOT_PROXY_URL "Enter proxy URL (socks5://user:pass@host:port or http://user:pass@host:port)"
  else
    BOT_PROXY_ENABLED=false
    BOT_PROXY_URL=""
  fi
}

install_packages() {
  log "Updating system packages..."
  export DEBIAN_FRONTEND=noninteractive
  apt-get update -y
  apt-get upgrade -y

  log "Installing Docker, Nginx, Certbot, and utilities..."
  apt-get install -y \
    ca-certificates curl gnupg lsb-release git ufw openssl wget \
    nginx certbot

  if ! command -v docker >/dev/null 2>&1; then
    install -m 0755 -d /etc/apt/keyrings
    curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg
    echo \
      "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu \
      $(. /etc/os-release && echo "$VERSION_CODENAME") stable" \
      > /etc/apt/sources.list.d/docker.list
    apt-get update -y
    apt-get install -y docker-ce docker-ce-cli containerd.io docker-compose-plugin
  fi

  systemctl enable docker
  systemctl start docker

  # Host nginx must not bind 80/443 — edge proxy runs in Docker
  systemctl stop nginx 2>/dev/null || true
  systemctl disable nginx 2>/dev/null || true
}

clone_or_update_repo() {
  if [[ -d "${INSTALL_DIR}/.git" ]]; then
    log "Repository exists at ${INSTALL_DIR} — pulling latest..."
    git -C "${INSTALL_DIR}" pull --ff-only origin main || git -C "${INSTALL_DIR}" pull --ff-only
  else
    log "Cloning repository to ${INSTALL_DIR}..."
    mkdir -p "$(dirname "${INSTALL_DIR}")"
    git clone "${REPO_URL}" "${INSTALL_DIR}"
  fi
}

write_env_file() {
  local env_file="${INSTALL_DIR}/.env"
  log "Writing ${env_file}..."
  cat > "${env_file}" <<EOF
# Generated by install.sh — $(date -u +"%Y-%m-%dT%H:%M:%SZ")
ENVIRONMENT=production
DEBUG=false
API_V1_PREFIX=/api/v1

POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
DATABASE_URL=postgresql+asyncpg://paycollection:${POSTGRES_PASSWORD}@postgres:5432/paycollection

JWT_SECRET_KEY=${JWT_SECRET_KEY}
JWT_ACCESS_TOKEN_EXPIRE_MINUTES=60
ADMIN_USERNAME=admin
ADMIN_PASSWORD=${ADMIN_PASSWORD}

DOMAIN=${DOMAIN}
CORS_ORIGINS=https://${DOMAIN}
TRUSTED_HOSTS=${DOMAIN},localhost,127.0.0.1,backend

INTERNAL_API_KEY=${INTERNAL_API_KEY}
BOT_TOKEN=${BOT_TOKEN}
BOT_HEALTH_URL=http://bot:8090/health
BOT_PROXY_ENABLED=${BOT_PROXY_ENABLED}
BOT_PROXY_URL=${BOT_PROXY_URL}

BACKEND_API_URL=http://backend:8000/api/v1
UPLOADS_DIR=/app/data/uploads/receipts
PAYMENT_CARD_NUMBER=
CHANNEL_ID=
CHANNEL_LINK=
ADMIN_TELEGRAM_ID=
REQUIRE_CHANNEL_JOIN=true
LOG_LEVEL=INFO
REFERRAL_DAILY_CAP=50
EOF
  chmod 600 "${env_file}"
}

render_nginx_config() {
  local template="$1"
  local output="$2"
  sed "s/__DOMAIN__/${DOMAIN}/g" "${template}" > "${output}"
}

prepare_directories() {
  mkdir -p \
    "${INSTALL_DIR}/deploy/nginx" \
    "${INSTALL_DIR}/deploy/certbot/conf" \
    "${INSTALL_DIR}/deploy/certbot/www" \
    "${INSTALL_DIR}/deploy/certbot/work" \
    "${INSTALL_DIR}/deploy/certbot/logs" \
    "${INSTALL_DIR}/deploy/backups"
}

build_and_start() {
  cd "${INSTALL_DIR}"
  log "Building Docker images..."
  docker compose -f "${COMPOSE_FILE}" build

  log "Starting services..."
  docker compose -f "${COMPOSE_FILE}" up -d

  log "Waiting for backend health..."
  local attempts=0
  until docker compose -f "${COMPOSE_FILE}" exec -T backend curl -fsS http://127.0.0.1:8000/health >/dev/null 2>&1; do
    attempts=$((attempts + 1))
    if [[ "${attempts}" -ge 60 ]]; then
      fail "Backend did not become healthy in time."
    fi
    sleep 2
  done
}

obtain_ssl_certificate() {
  log "Requesting SSL certificate for ${DOMAIN}..."
  certbot certonly --webroot \
    -w "${INSTALL_DIR}/deploy/certbot/www" \
    -d "${DOMAIN}" \
    --email "${EMAIL}" \
    --agree-tos \
    --non-interactive \
    --config-dir "${INSTALL_DIR}/deploy/certbot/conf" \
    --work-dir "${INSTALL_DIR}/deploy/certbot/work" \
    --logs-dir "${INSTALL_DIR}/deploy/certbot/logs"

  render_nginx_config \
    "${INSTALL_DIR}/deploy/nginx/production.conf.tpl" \
    "${INSTALL_DIR}/deploy/nginx/active.conf"

  docker compose -f "${INSTALL_DIR}/${COMPOSE_FILE}" restart nginx
}

configure_firewall() {
  log "Configuring UFW firewall..."
  ufw --force reset
  ufw default deny incoming
  ufw default allow outgoing
  ufw allow OpenSSH
  ufw allow 80/tcp
  ufw allow 443/tcp
  ufw --force enable
}

install_cli() {
  install -m 0755 "${INSTALL_DIR}/deploy/bin/paycollection" /usr/local/bin/paycollection
  log "CLI installed: paycollection"
}

health_check() {
  log "Running final health check..."
  local url="https://${DOMAIN}/health"
  local attempts=0
  until curl -fsS "${url}" >/dev/null 2>&1; do
    attempts=$((attempts + 1))
    if [[ "${attempts}" -ge 30 ]]; then
      warn "HTTPS health check failed — trying HTTP..."
      curl -fsS "http://${DOMAIN}/health" || fail "Health check failed."
      return
    fi
    sleep 3
  done
  curl -fsS "${url}" | head -c 500
  echo
}

setup_certbot_renewal() {
  local hook="${INSTALL_DIR}/deploy/scripts/certbot-renew-hook.sh"
  chmod +x "${hook}"
  cat > /etc/cron.d/paycollection-certbot <<EOF
0 3 * * * root certbot renew --quiet \\
  --config-dir ${INSTALL_DIR}/deploy/certbot/conf \\
  --work-dir ${INSTALL_DIR}/deploy/certbot/work \\
  --logs-dir ${INSTALL_DIR}/deploy/certbot/logs \\
  --deploy-hook ${hook}
EOF
}

main() {
  require_root

  echo "=============================================="
  echo " PayCollectionBOT — Production Installer"
  echo "=============================================="

  prompt_required DOMAIN "Enter admin panel domain (e.g. panel.example.com)"
  prompt_required EMAIL "Enter email for Let's Encrypt"
  prompt_required BOT_TOKEN "Enter Telegram Bot Token"
  prompt_required ADMIN_PASSWORD "Enter admin panel password (min 8 chars)"

  if [[ ${#ADMIN_PASSWORD} -lt 8 ]]; then
    fail "Admin password must be at least 8 characters."
  fi

  POSTGRES_PASSWORD="$(rand_hex 16)"
  JWT_SECRET_KEY="$(rand_hex 32)"
  INTERNAL_API_KEY="$(rand_hex 32)"

  prompt_telegram_proxy

  install_packages
  clone_or_update_repo
  chmod +x "${INSTALL_DIR}/install.sh" \
    "${INSTALL_DIR}/deploy/bin/paycollection" \
    "${INSTALL_DIR}/deploy/scripts/"*.sh 2>/dev/null || true
  prepare_directories

  render_nginx_config \
    "${INSTALL_DIR}/deploy/nginx/http.conf.tpl" \
    "${INSTALL_DIR}/deploy/nginx/active.conf"

  write_env_file
  build_and_start
  obtain_ssl_certificate
  setup_certbot_renewal
  configure_firewall
  install_cli
  health_check

  echo
  log "Installation complete!"
  echo "  Panel URL : https://${DOMAIN}"
  echo "  Admin user: admin"
  echo "  Admin pass: (the password you entered)"
  echo "  Update    : paycollection update"
  echo "  Backup    : paycollection backup"
  echo
  warn "Save your .env file securely: ${INSTALL_DIR}/.env"
}

main "$@"
